name: fitnessworld
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  syncfusion_flutter_gauges: ^28.2.4
  numberpicker: ^2.1.2
  dotted_border: ^2.1.0
  pin_code_fields: ^8.0.1
  fl_chart: ^0.70.2
  slide_to_act: ^2.0.2
  flutter_heatmap_calendar: ^1.0.5
  scrollable_clean_calendar: ^1.5.0
  flutter_xlider: ^3.5.0
  http: ^1.3.0
  animated_notch_bottom_bar: ^1.0.3
  scroll_to_animate_tab: ^0.0.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/fonts/


  # example:
  fonts:
     - family: Main
       fonts:
         - asset: assets/fonts/WorkSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
